2024-09-03 21:56:12,960 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-03 21:56:12,960 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-03 21:57:11,423 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-03 21:57:11,423 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-03 21:57:14,761 - chromadb.segment.impl.vector.local_hnsw - WARNING - query_vectors - 138- Number of requested results 4 is greater than number of elements in index 3, updating n_results = 3
2024-09-04 20:03:00,767 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-04 20:03:00,768 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-04 20:09:17,972 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 1.8s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016FC00DE210>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-04 20:09:19,820 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 1.3s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016FC00DE4E0>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-04 20:09:21,105 - backoff - ERROR - _log_giveup - 120- Giving up send_request(...) after 4 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016FC00DEA20>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-04 20:09:26,108 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-04 20:09:26,108 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-04 20:09:26,200 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 0.5s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016FC01577A0>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-04 20:09:26,706 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 0.7s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016FC0155DC0>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-04 20:09:27,417 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 2.4s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016FC0155A90>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-04 20:09:29,844 - backoff - ERROR - _log_giveup - 120- Giving up send_request(...) after 4 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016FC0155640>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-04 20:10:12,393 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 0.1s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016FC0F5E9F0>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-04 20:10:12,540 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 1.4s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016FC1ED6D20>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-04 20:10:13,893 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 3.6s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016FC1ED6F00>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-04 20:10:17,549 - backoff - ERROR - _log_giveup - 120- Giving up send_request(...) after 4 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016FC01559A0>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-04 20:10:18,062 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 0.8s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016FC1ED7EC0>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-04 20:10:18,915 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 0.5s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016FC1F70110>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-04 20:10:19,444 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 1.7s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016FC1F702F0>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-04 20:10:21,199 - backoff - ERROR - _log_giveup - 120- Giving up send_request(...) after 4 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016FC1F70860>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-04 20:11:36,746 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-04 20:11:36,747 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-04 20:11:59,865 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-04 20:11:59,865 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-04 20:34:32,728 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-04 20:34:32,728 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-04 20:37:29,223 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-04 20:37:29,224 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-04 20:38:24,731 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-04 20:38:24,731 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-04 20:50:00,136 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-04 20:50:00,136 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-04 20:50:20,720 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-04 20:50:20,720 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-04 20:52:35,227 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-04 20:52:35,227 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-04 21:05:28,295 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-04 21:05:28,295 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-05 22:39:44,789 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-05 22:39:44,789 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-05 22:40:15,129 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-05 22:40:15,129 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-17 10:51:18,113 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-17 10:51:18,113 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-17 10:52:20,694 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-17 10:52:20,694 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-17 12:43:28,549 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-17 12:43:28,549 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-17 12:44:01,335 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-17 12:44:01,336 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-17 12:44:34,448 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-17 12:44:34,448 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
